export const cars = [
    {
        "id": 1,
        "price": "₹3,00,000",
        "model": "Honda City",
        "year": 2018,
        "condition": "Used",
        "image": "https://stimg.cardekho.com/images/carexteriorimages/930x620/Honda/City/9710/1677914238296/front-left-side-47.jpg",
        "brand": "Honda",
        "location": "Chennai",
        "kmDriven": "35,000 km",
        "seats": 5,
        "fuelType": "Petrol",
        "transmission": "Automatic",
        "color": "White",
        "engine": "1.5L",
        "owners": 1,
        "serviceHistory": "Full",
        "insurance": "Valid until 2025"
      },
      {
        "id": 2,
        "price": "₹4,50,000",
        "model": "Honda Civic",
        "year": 2017,
        "condition": "Used",
        "image": "https://imgd.aeplcdn.com/664x374/n/cw/ec/27074/civic-exterior-right-front-three-quarter-148156.jpeg?q=80",
        "brand": "Honda",
        "location": "Salem",
        "kmDriven": "40,000 km",
        "seats": 5,
        "fuelType": "Diesel",
        "transmission": "Manual",
        "color": "Black",
        "engine": "1.8L",
        "owners": 2,
        "serviceHistory": "Partial",
        "insurance": "Valid until 2024"
      },
    {
      "id": 3,
      "price": "₹5,20,000",
      "model": "Honda Accord",
      "year": 2016,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Honda",
      "location":"Namakkal"
    },
    {
      "id": 4,
      "price": "₹3,75,000",
      "model": "Honda Jazz",
      "year": 2019,
      "condition": "Used",
      "image": "https://imgd.aeplcdn.com/1280x720/n/cw/ec/46891/jazz-exterior-right-front-three-quarter.jpeg?q=80",
      "brand": "Honda",
      "location":"Karur",
    },
    {
      "id": 5,
      "price": "₹6,80,000",
      "model": "Honda CR-V",
      "year": 2020,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Honda",
      "location":"Chennai",
    },
    {
      "id": 6,
      "price": "₹7,00,000",
      "model": "Honda Amaze",
      "year": 2021,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Honda",
      "location":"Chennai",
  
    },
    {
      "id": 7,
      "price": "₹3,20,000",
      "model": "Maruti Swift",
      "year": 2019,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Maruti",
      "location":"Chennai",
  
    },
    {
      "id": 8,
      "price": "₹4,75,000",
      "model": "Maruti Baleno",
      "year": 2020,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Maruti",
      "location":"Chennai",
  
    },
    {
      "id": 9,
      "price": "₹5,50,000",
      "model": "Maruti Vitara Brezza",
      "year": 2018,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Maruti",
      "location":"Chennai",
  
    },
    {
      "id": 10,
      "price": "₹3,90,000",
      "model": "Maruti Dzire",
      "year": 2019,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Maruti",
      "location":"Chennai",
  
    },
    {
      "id": 11,
      "price": "₹4,30,000",
      "model": "Hyundai Verna",
      "year": 2017,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    },
    {
      "id": 12,
      "price": "₹5,60,000",
      "model": "Hyundai Creta",
      "year": 2018,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    },
    {
      "id": 13,
      "price": "₹4,20,000",
      "model": "Hyundai i20",
      "year": 2019,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    },
    {
      "id": 14,
      "price": "₹3,80,000",
      "model": "Hyundai Grand i10",
      "year": 2018,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    },
    {
      "id": 15,
      "price": "₹6,00,000",
      "model": "Hyundai Tucson",
      "year": 2017,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    },
    {
      "id": 16,
      "price": "₹7,50,000",
      "model": "Hyundai Elantra",
      "year": 2020,
      "condition": "Used",
      "image": "https://www.motortrend.com/uploads/sites/5/2021/05/2021-honda-accord-sport-2-0t-15.jpg",
      "brand": "Hyundai",
      "location":"Chennai",
  
    }
  ]
